### ISSUE TITLE
Discussion | Support ZK-STARKs

### ISSUE THREAD

**Issue by ghbjklhv** [Anoncoin/anoncoin#29]
**Goal**: Implement and Support [ZK-STARKs](https://medium.com/coinmonks/zk-starks-create-verifiable-trust-even-against-quantum-computers-dd9c6a2bb13d) in AnonCoin
**Description**: Let's consider how to integrate and use ZK-STARKs, possibly leveraging the work upstream. 
**Why?**: To make transactions full anonymous and verifiable. 

______________________________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75435282-discussion-support-zk-starks)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=75435282)](https://www.bountysource.com/issues/75435282-discussion-support-zk-starks)

**Comment by GroundRod** [comment]
Hay ghbjklhv,

ya I'm open to working on code again, including ZK integration for
AnonCoin, if that is what the community wants, it could mean allot to the
project.  Early on, this was a main focus, allot has been learned about
ZeroKnowledge since then, allot has been done to address this Item: 'assume
that when using a ZK-SNARK system, the trusted setup phase is secure'

So maybe your call to implement that now, is the right time. Just saying....
Fact is I've been out of the loop since '14-15, and allot has changed in
the Crypto world, plus Meeh is back & may have goals I can only guess at.
Have not had any contact with him or the Dev Team until now, so do not know
anymore than the rest of you.

**Comment by GroundRod** [comment]
ghbjklhv - I'm going to close this topic as an issue for now.  We are all aware of the need and desire to move toward solutions like Zero Knowledge can provide. Its a large and complex topic.

Getting a new road map together, where this may or may not be included depends allot on manpower and what Meeh wants us to focus on, after all, we are fortunate to still have the coin's Inventor alive and involved in the project.  How many coins can you say that for? Not many.  This topic is important ghbjklhv, it will not be forgotten...

GR
